config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'portfolio' => 'pages#portfolio'
  get 'parcours' => 'pages#parcours'
  get 'contact' => 'pages#contact'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	# Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "JulieFirstSite"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <p>© Tous droits réservés Julie Alary //  except background  <a href='http://www.freepik.com/free-vector/striped-black-background_801315.htm'>par Freepik</a></p>
  </small>
  <nav>
    <ul>
      <li></li>
    </ul>
  </nav>

</footer>

app/views/layouts/_header.html.erb
<header>
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid fluid_nav">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle Navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="#">Julie Alary</a>
    </div>
    <div class="collapse navbar-right navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "| Accueil |",      root_path %></li>
        <li><%= link_to "| Réalisations |",    portfolio_path %></li>
        <li><%= link_to "| Parcours |",     parcours_path %></li>
        <li><%= link_to "| Contact |",      contact_path %></li>
      </ul>
      
    </div>
  </div>
</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='https://fonts.googleapis.com/css?family=Ubuntu&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
  

  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
  
</head>
<body>
  <%= render 'layouts/header' %>
    <!--<div class="container"> Si je le fait apparaitre cela me crée des marges g et d-->
<%= yield %>
<%= render 'layouts/footer' %>
	<!--</div>-->
</body>
</html>

app/views/pages/contact.html.erb
		<div class="bground">

    <div class="row contact_head">
        <h1> Contactez- moi !! </h1>
        <h3> ...ou bien...</h3><br/>
        <h5> Follow[ez]-moi | Add[ez]-moi | Fork[ez]-moi</h5>

    </div>

    <div class="row contact1">
        <div class="col-xs-4 col-md-4">
            <div class="flip4"><i class="fa fa-twitter"></i></div>
            <div class="panel4"><a class="twitter-timeline" href="https://twitter.com/julie_alary" data-widget-id="708459886145880066">Tweets de @julie_alary</a> <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
            </div>
        </div>

  		  <div class="col-xs-4 col-md-4">
  			     <a href="https://www.facebook.com/julie.alary1"><i class="fa fa-facebook"></i> </a>
  		  </div>

  		  <div class="col-xs-4 col-md-4">
  			     <a href="mailto:julie.alary@gmail.com"><i class="fa fa-envelope-o"></i></a>
  		  </div>
    </div>
    <div class="row contact2">
  		  <div class="col-xs-4 col-md-4">
             <a href="https://www.linkedin.com/in/juliealary?trk=nav_responsive_tab_profile"/><i class="fa fa-linkedin"></i></a>
        </div>

        <div class="col-xs-4 col-md-4">
 			      <a href="https://bitbucket.org/Ju31/"><i class="fa fa-bitbucket"></i></a>
        </div>

        <div class="col-xs-4 col-md-4">
            <a href="https://github.com/JulieAlary"><i class="fa fa-github-alt"></i></a>
        </div>
    </div>
    <div class="row contact3">
        <div class="col-xs-4 col-md-4">
             <a href="http://codepen.io/Julie31/"/><i class="fa fa-codepen"></i></a>
        </div>

        <div class="col-xs-4 col-md-4">
            <a href="https://www.reddit.com/user/Juju31/"><i class="fa fa-reddit-alien"></i></a>
        </div>

        <div class="col-xs-4 col-md-4">
            <a href="#"></a>
        </div>
    </div>
  </div>

app/views/pages/home.html.erb
		<div class="jumbotron text-center">
			<h1> Web conceptrice en devenir </h1>
		</div>

		<div class = "container-fluid section2 text-center">
			<h3>Précédemment Responsable dans la Vente,  <br/>je souhaite aujourd'hui me reconvertir dans le développement web<br/>étant passionnée depuis l'enfance</h3>
		</div>
			<div class="container-fluid">
		<div class="row mon_parcours">
			<div class="col-md-6 text-center">
				<h3>Mon parcours</h3>
			</div>
			<div class="col-md-6">	
				<a href="https://ancient-tundra-13925.herokuapp.com/parcours"><img src="images/evolution_informatique.jpg" id="img_evolution_informatique" alt="evolution de l'homme" class="img-responsive"/></a>
			</div>
		</div>
	</div>

		<div class="container-fluid explications">
			<h3> Le site sera en constante évolution au gré de mon apprentissage et des diverses réalisations effectuées</h3>
		</div>
		
		<div class="container-fluid">
		<div class="row outil">
			<h1> Site réalisé avec : </h1>
			<div class="col-xs-4 col-md-4 outil_title">
				<a href="http://rubyonrails.org"><img src="images/rails-logo.svg" alt="logo RoR" id="Logo_ror"class="img-responsive"alt="logo-rails" /></a>
			</div>

			<div class="col-xs-3  col-md-4 outil_title">
				<img src="images/HTML5_CSS3_Logos.svg"class="img-responsive"alt="logo html css"/>
			</div>
			<div class="col-xs-3  col-md-4 outil_title">
				<a href="http://jquery.com"><img src="images/jQuery.gif" class="img-responsive" id="logo_jquery2" alt="logo JQuery"/></a>
			</div>
			<div class=" col-md-4 col-md-offset-4">
				<a href ="http://getbootstrap.com"><img src="images/Boostrap_logo.svg" class="img-responsive" id="logo_boostrap" alt="Logo Boostrap"/></a>
			</div>
		</div>
	</div>

app/views/pages/parcours.html.erb
<div class="container-fluid section_cv"id="cv">
	<div class="row title_cv">
		<div class="col-xs-6 col-md-6">
			<h3>Mon Cv</h3>
		</div>
		<div class="col-xs-6 col-md-6">
			<div class="flip5">
				<i class="fa fa-file-text-o"></i>
			</div>
		</div>
	</div>
	<div class="row upload_cv">
		<div class="col-md-6 col-md-offset-4">
			<button type="button" class="btn btn-default btn-lg btn-block ">
				<a href="/pdf/CV-Julie-Alary-2016.pdf">Download CV PDF</a>
			</button>
		</div>
	<div class ="row arrow1">
		<div class="col-md-4 col-md-offset-4">
			<p><a href="#codecademy"><i class="fa fa-arrow-down"></i></a></p>
		</div>
	</div>


	</div>
         <div class="panel5">
			<div class="panel_content">	
				<div class="entete_cv">
    				<h1>Julie Alary</h1>
						<h4>En reconversion professionnelle
							Apprentissage de html, css, ruby, utilisation de cms</h4>
    			</div>
    				<div class ="row cv_grid">
    					<div class="col-md-4 exprience">
    						
    							<h4>Expériences</h4>
    							<div class="deleguee">
    								<h5>DELEGUEE COMMERCIALE : aout 2015 à février 2016</h5>
 									<p>Commerciale pour une maison d'édition : phonning, prise de rendez-vous, vente directe, reporting.</p>
 									<br/>
 								</div>
 								<div class="croissanterie">
 									<h5>RESPONSABLE DES VENTES : 2013-aujourd'hui</h5>
									<p>Management d'une équipe de 10 vendeurs (recrutement, planning, formation) répartis sur deux points de vente, gestion des stocks (commandes, inventaires), gestion de la caisse (remise en banque), dynamisation des ventes (techniques de vente, opérations de fidélisation, mise en valeur de l'espace de vente).Enseigne La Croissanterie (restauration rapide), Portet sur Garonne.</p>
									<br/>
								</div>
								<div class="internity">
									<h5>RESPONSABLE POINT DEVENTE : 2008-2012</h5>
									<p>Conception et mise en place de l'organisation de l'unité de vente (management,formation, planning...) agencement et mise en valeur de l'espace de vente, suivi des stocks ( commandes, inventaires), gestion de la caisse (comptage et remise en banque), gestion du Service Après Vente ( maintenance informatique en boutique ou via une plateforme dédiée), mise en place de diverses actions de communication avec des partenaires locaux. Enseigne Internity (téléphonie, multimédia), Castres.</p>
									<br/>
								</div>
								<div class="mcdo">
									<h5>MANAGER DE LA RESTAURATIONRAPIDE: 2006-2008</h5>
									<p>Management d'une équipe de 10 à 25 équipiers, gestion opérationnelle du terrain, connaissance des règles d'hygiènes, gestion des écarts-rendement, comptage et remise en banque, formation des équipes. Enseigne McDonald's, Castelnaudary.</p>
									</br>
								</div>
							<h4>Autres : </h4>
								<div class="autre">
									<h5>Animatrice diplômée:</h5> 
									<p>Vacances scolaires 2002 à 2006 </p>
									<p>Encadrement et animation de groupes d'enfants de 3 à 16 ans. Centre de loisirs de Besplas, Villassavary.</p>
								</div>	
						
						</div>
  						<div class="col-md-4 competence">
  							
  							<h4>Compétences Management</h4>
  								<div class="management">
  								<p>Techniques de vente et merchandising</p>
								<p>Gestion comptable et administrative</p>
								<p>Modalité d'accueil client</p>
								<p>Règles de gestion de stocks</p>
								<p>Management d'une équipe</p>
								<p>Législation sociale et droit commercial</p>
								<p>phonning</p>
								<p>Maîtrise de l'outil informatique (utilisation et maintenance)</p>
								</div>
  							<h4>Compétences Informatique</h4>
  								<div class="informatique">
  								<p>HTML5 / CSS3</p>
  								<p>Ruby on rails - niveau intermédiaire</p>
  								<p>JavaScript / jQuery - niveau débutant</p>
  								<p>Java - niveau débutant</p>
  								<p>PHP / Sql - niveau débutant</p>
  								<p>Git</p>
  								</div>
						</div>
  						<div class="col-md-4">
  							
  							<h4>Formation</h4>
  							<div class="formation">
  								<p>DEUG Géographie 2005 (non obtenu) - Univerisité Toulouse II (31)<p>
  								<p>Baccalauréat Economie 2002 - Lycée Paul Sabatier Carcassonne (11)<p>
  							</div>
  							
  							<h4>Divers</h4>
  							<div class="divers">
  								<p>Permis B</p>
  								<p>Langues parlées : Anglais, Espanol - niveau scolaire</p>
  							</div>
  							
  							<h4>Passion / Hobbies</h4>
  							<div class="hobbies">
  								<p>Snowboard</p>
  								<p>Musique : guitare, djjing</p>
  								<p>Sorties culturelles : théatre, expositions, cinéma</p>
  								<p>Voyages</p>
  							</div>
  						</div>
            		</div>
				</div>
         	</div>
         </div>	
</div>
<!------------------------------------------------------------------------>
<div class="container-fluid section_logo"id="codecademy">
	<div class="row codecademy">
		<div class=" col-md-12">
			<h3> Courses done @ Codecademy</h3>
				<a href="https://www.codecademy.com/fr/users/julie_alary/achievements"><img src="images/logo_codeCademy.png" class="img-responsive img_codecademy"/></a>
			</div>
	</div>
	<div class="row logo_langages">
		<div class="col-xs-3 col-md-2">
			<img src="images/html5.png" alt="logo html5 " class="img-responsive"/>
		</div>
		<div class="col-xs-3  col-md-2">
			<img src="images/css3.png" alt="logo css3 " class="img-responsive"/>
		</div>
		<div class="col-xs-3  col-md-2">
			<img src="images/JS.png" alt="logo javascript" class="img-responsive"/>
		</div>
		<div class="col-xs-3  col-md-2">
			<img src="images/php.png" alt="logo php5" class="img-responsive"/>
		</div>
		<div class="col-xs-3  col-md-2">
			<img src="images/jQuery.gif" width="75px"alt="logo jquery" class="img-responsive"/>
		</div>
		<div class="col-xs-3  col-md-2">
			<img src="images/logoRuby.png" width="75px" alt="logo ruby" class="img-responsive"/>
		</div>
	</div>
	<div class="row logo_langage2">
		<div class=" col-xs-3 col-md-2">
			<img src="images/rails-logo.svg" width="75px" alt="logo ruby on rails" class="img-responsive"/>
		</div>
		<div class="col-xs-3  col-md-2">
			<img src="images/logo_git.png" width="75px" alt="logo git" class="img-responsive"/>
		</div>
		<div class="col-xs-3  col-md-2">
			<img src="images/Boostrap_logo.svg" width="75px" alt="logo boostrap" class="img-responsive"/>
		</div>
		<div class="col-xs-3  col-md-2">
			<img src="images/angularjs.svg" width="75px" alt="angular" class="img-responsive"/>
		</div>
		<div class="col-xs-3  col-md-2">
			<img src="images/java.svg" width="75px" alt="logo java" class="img-responsive"/>
		</div>
		<div class="col-xs-3  col-md-2">
			<img src="images/mysql.svg" width="75px" alt="logo git" class="img-responsive"/>
		</div>
	</div>
	<div class="row arrow2">
		<div class="col-md-4 col-md-offset-4">
			<p><a href="#open"><i class="fa fa-arrow-down"></i></a><a href="#cv"><i class="fa fa-arrow-up"></i></a></p>
		</div>
	</div>
</div>


<div class="container-fluid section_open"id="open">	
	<h3> Certificats de réussite OpenClassRoom</h3>
	<br/>
	<a href="https://openclassrooms.com/"><img src="images/logo_openClassRoom.png" alt"logo OpenClassRoom" class="img-responsive img_open"/></a>
	<br/>
	<br/>
	<br/>

<div class= "row certif">
	<div class="col-xs-6 col-md-6">
		<div class="flip">Apprenez à créer votre site web avec HTML5 et CCS3<br/>Certificat de réussite OpenClassRoom</div>
		<div class="panel"><img src="images/certificat_html_css.jpg"class="img-responsive"/></div>
	</div>

	<div class="col-xs-6 col-md-6">
		<div class="flip2">Concevez votre site avec PHP et MySQL<br/>Certificat de réussite OpenClassRoom</div>
		<div class="panel2"><img src="images/certificat_PHP_MySQL.jpg"class="img-responsive"/></div>
	</div>

	<div class="col-xs-6 col-md-6">
		<div class="flip3">Gérer son code avec Git et Github<br/>Certificat de réussite OpenClassRoom</div>
		<div class="panel3"><img src="images/certificat_git_github.jpg"class="img-responsive"/></div>
	</div>
</div>
<div class="row arrow3">
		<div class="col-md-4 col-md-offset-4">
			<p><a href="#cv"><i class="fa fa-arrow-up"></i></a></p>
		</div>
</div>
</div>

app/views/pages/portfolio.html.erb
<div class ="container-fluid container1">
    <div id="cont1">
        <div class="cd-intro">
            <div class="cd-intro-content bouncy">
                <div class="row">
                    <div class="col-md-6 portfolio_p">
                        <p>Vous trouverez ici l'ensemble de mes travaux</p>
                    </div>
                    <div class="col-md-6">
                        <h1>MES REALISATIONS</h1>
                    </div>
                </div>
                <div class="row action-wrapper">
                    <div class="col-md-6">
                        <h6>Conception Site</h6>
                            <a href="#cont" class="cd-btn main-action"><img src ="/images/thumb.jpg"class="img-responsive" id="icone_site_builder"></a>
                    </div>
                    <div class="col-md-6">	
                        <h5>Créations diverses</h5>
                            <a href="#cont" class="cd-btn"><img src="/images/pink_invaders.gif"class="img-responsive" id="pink_invader"></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid container2">
    <div id="cont">
        <h1> SOON...STAY CONNECTED....</h1>
            <div class="row folio_anim">
                <div class="view view-first">
                    <img src="/images/santigold.jpg"class="img-responsive"alt="santigold"></a>  
                        <div class="mask">
                            <h2>One Page Site</h2>
                            <p>A tribute page about the artist Santigold (an exercice for FreeCodeCamp)</p>
                            <a href="https://s.codepen.io/Julie31/debug/rezxGd" class="info">See the Site</a>
                        </div>
                    </div>
                <div class="view view-first">
                    <img src="/images/random.jpg"class="img-responsive" alt="random quote"/>
                        <div class="mask">
                            <h2>Random Lyrics</h2>
                            <p>A random lyric about Santigold's (An excercice for FreeCodeCamp about random quote generator)</p>
                            <a href="http://s.codepen.io/Julie31/debug/yOzyaV" class="info">See the generator</a>
                        </div>
                    </div>
                <div class="view view-first">
                    <img src="/images/portfolio.jpg" alt="portfolio" class="img-responsive" />
                        <div class="mask">
                            <h2>One page Portfolio</h2>
                            <p>A one page portofolio about myself (an exercice for FreeCodeCamp)</p>
                            <a href="http://s.codepen.io/Julie31/debug/EKvyEm" class="info">See the Portfolio</a>
                        </div>
                    </div>
                <div class="view view-first">
                    <img src="/images/gif_mysteres_de_l'amour.gif" /> 
                        <div class="mask">
                            <h2>A funny gif</h2>
                            <p>Made with Giphy - Just for fun...</p>
                            <a href="http://giphy.com/gifs/gNGXnJgqKP5uw/fullscreen" class="info">See full screen</a>
                        </div>
                    </div>
                <div class="view view-first">
                    <img src="/images/pink_invaders.gif" />
                        <div class="mask">
                            <h2>Creation Sprite</h2>
                            <p>Creation de sprite avec piskel</p>
                            <a href="http://www.piskelapp.com" class="info">Piskel</a>
                        </div>
                    </div>
                <div class="view view-first">
                    <img src="" alt="" class="" />
                        <div class="mask">
                            <h2>Soon Other project</h2>
                            <p>blabla</p>
                            <a href="#" class="info">See Soon</a>
                        </div>
                    </div>
                <div class="view view-first">
                    <img src="" alt="" class="" />
                        <div class="mask">
                            <h2>Soon Other project</h2>
                            <p>blabla</p>
                            <a href="#" class="info">See Soon</a>
                        </div>
                    </div>
                <div class="view view-first">
                    <img src="" alt="" class="" />
                        <div class="mask">
                            <h2>Soon Other project</h2>
                            <p>blabla</p>
                            <a href="#" class="info">See Soon</a>
                        </div>
                    </div>
                </div>
            </div>
    <!-- </div>  -->
        <div class="row last_section">
            <div class="col-xs-6"><p>
                <a href="#cont3">
                    <span class=""></span>
                    </a>
                </p>
            </div>
            <div class="col-xs-6"><p>
                <a href="#cont1">
                    <span class="glyphicon glyphicon-chevron-up"></span>
                    </a>
                </p>
            </div>
        </div>
    </div>
</div>


  

    <div class="invaders_animation">
        <a href="http://www.piskelapp.com/user/5247310938243072/public" onclick="window.open(this.href); return false;"><img id="invaders" src="./images/first_gif.gif" width="150px" alt="blue invaders" data-toggle="tooltip" data-placement="left" title="Invader designed with Piskel"></a>
    </div>


    